= CI Setup for Ansible Playbook
:latestRevision: 1.0.0
:toc:

== Summary
The Ansibles roles, described here, are intended to set up a continues integration environment using Sonatype Nexus and Jenkins.

=== Preconditions:
* https://www.centos.org/[CentOS 7] machine
* Installed http://docs.ansible.com/ansible/intro.html[Ansible]
* Internet access

== Quick Installation Guide

# Install Ansible.
`yum -y install epel-release`
`yum -y install ansible`
# Copy the contents of this repository to _/etc/ansible_.
# Copy _host_vars/sample.yml_ to _host_vars/<yourhost>.yml_ and configure the values. For details see section <<Configuration>>.
# Run the Ansible playbook
`ansible-playbook setupci.yml`

== Sample Playbooks

=== setupci.yml
This playbook sets up a complete CI environment including:

* Oracle Java JDK
* Oracle Server
* Oracle Client
* Nexus
* Jenkins
* Project setup
* Initialization of git (GitLab) or SVN (Subverssion) repositories

=== ishsystem.yml
This playbook sets up a new host to deploy an Intershop Commerce Management system including:

* Oracle Java JDK
* Oracle Server
* Oracle Server
* User to execute the deployment and to set up the Intershop environment

== Roles

=== cisetup
Role to create project user / groups. This role also:

* Executes the project-bootstrap tasks
* Imports the responsive starter store
* Initialize the SVN repositories, or git-repositories on GitLab server

=== ishsetup
Role to create an environment to execute an Intershop server deployment.

=== jenkins
Role to install Jenkins. Currently there is no configuration for Jenkins included.

=== nexus
Role to install and configure the Nexus. All required repositories and proxy-repositories are created by this role.

=== oracle-client
Installs Oracle Client. Currently this role is only tested with Oracle 12.1.0.2.

=== oracle-server
Installs Oracle Server. Currently this role was only tested with Oracle 12.1.0.2 (EE).

=== oraclejdk
Role to install the Oracle JDK

== Configuration
Default values for the roles are configured in _roles\*\defaults\main.yml_
Commented values needs to be set. Unconfigured commented values needs to be defined in `host_vars` or `group_vars`.

NOTE: It is highly recommended to encrypt sensitive data like passwords, user tokens and licenses with Ansible vault. See http://docs.ansible.com/ansible/playbooks_vault.html[Ansible documentation] for details.
Use group_vars/sample.yaml as a start-point.
[cols="17%,17%,85%", width="90%, options="header"]
|===
|Name | Sample | Description
3+| *ROLE CISETUP* / ishsetup
| *ish_user_sshkey*   | `-----BEGIN RSA PRIVATE KEY ...` | ssh-Key for GitLab pushes
| *ish_password*      | `$1$...`            | Encrypted password. See http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module[Ansible documentation] for details
| *ish_corporateName* | `com.example`       | Provide a reverse domain name
| *ish_projectName*   | `corporateshop`     | Provide a name using only letters, numbers and underscores (no spaces or other special characters)
| *ish_license*       | `<?xml version ...` | Provide the contents of your Intershop License File
3+| *SVN-Configuration*
| *ish_svn_baseurl* | `\https://svn.example.com/svn/myproject/source`| SVN Base URL
| *ish_svn_username* | `myuser`             | Username for SVN access
| *ish_svn_password* | `password`           | Password for SVN access
3+| *Git / gitlab-Configuration*
| *ish_gitlab_token* | `yourtoken`          | Token for GitLab access
| *ish_gitlab_server_url* | `\https://gitlab.example.com` | GitLab server URL
| *ish_gitlab_group* | `corporateshop` | Group for the repositories to initialize
| *ish_git_user_name* | `gituser` | User name of the git user
| *ish_git_user_email* | `gituser@example.com` | Email address of the git user
3+| *ROLE NEXUS*
| *nexus_ishrepo_url* | `\https://repo.intershop.de/content/repository/4711` | URL to access Intershop Repository server
| *nexus_ishrepo_user* | `usertoken` | User token to access Intershop Repository server
| *nexus_ishrepo_password* | `secret` | Password for the user token
3+| *ROLE ORACLE-CLIENT*
| *oracle_client_download_url* | `\https://install.example.com/oracle/linuxamd64_12102_client.zip` | Location for Oracle client installation file
3+| *ROLE ORACLE-SERVER*
| *oracle_server_download_files* | `\https://install.example.com/oracle/linuxamd64_12102_database_1of2.zip` +
`\https://install.example.com/oracle/linuxamd64_12102_database_1of2.zip` | Location for Oracle server installation files
|===

For more information please see

* https://support.intershop.com/kb/index.php/Display/X27327[Cookbook - Setup CI Infrastructure (valid to Gradle Tools 2.7)]

== License

Copyright 2014-2016 Intershop Communications.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.