= ci setup ansible playbook
:latestRevision: 1.0.0
:toc:

== Summary
This ansibles roles are intended to setup a continues integration environment using nexus and jenkins.

=== Preconditions:

* https://www.centos.org/[CentOS 7] machine
* Installed http://docs.ansible.com/ansible/intro.html[Ansible]
* Internet access

== Sample playbooks

=== setupci.yml
This playbook setup a complete ci environment including

* Oracle Java JDK
* Oracle Server
* Oracle Client
* Nexus
* Jenkins
* project setup
* Initialization of git (gitlab) or svn repositories

=== ishsystem.yml
This playbook setup a new host for deploying an intershop system

* Oracle Java JDK
* Oracle Server
* Oracle Server
* User for running deployment and intershop environment

== Roles

=== cisetup
Role for create project user / groups. This role also execute the project-bootstrap tasks and imports the responsive starter store. SVN repositories or git-repositories on gitlab-Server are initialized by this role

=== ishsetup
Role for creating an environment to execute an intershop server deployment.

=== jenkins
Role for installing Jenkins. For now there is no configuration of Jenkins included.

=== nexus
Role for installing and configuring nexus. All needed repositories and proxy-repositories are created by this role.

=== oracle-client
Installs Oracle Client. For now this role was only tested with Oracle 12.1.0.2

=== oracle-server
Installs Oracle Server. For new this role was only tested with Oracle 12.1.0.2 (EE)

=== oraclejdk
Role for installing Oracle JDK

== Configuration

Default values for the roles are configured in `roles\*\defaults\main.yml`
Commented values needs to be set. Unconfigured commented values needs to be defined in `host_vars` or `group_vars`. *It is highly recommended to encrypt sensitive data like passwords, user tokens and licenses with Ansible vault. See http://docs.ansible.com/ansible/playbooks_vault.html[Ansible documentation] for details
[cols="17%,17%,85%", width="90%, options="header"]
|===
|Name | Sample | Description
3+| *ROLE CISETUP* / ishsetup
| *ish_user_sshkey*   | `-----BEGIN RSA PRIVATE KEY ...` | ssh-Key for gitlab pushes
| *ish_password*      | `$1$...`            | Encrypted password. See http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module[Ansible documentation] for details
| *ish_corporateName* | `com.example`       | Provide a reverse domain name
| *ish_projectName*   | `corporateshop`     | Provide a name using only letters, numbers and underscores (no spaces or other special characters)
| *ish_license*       | `<?xml version ...` | Provide the contents of your Intershop License File
3+| *SVN-Configuration*
| *ish_svn_baseurl* | `https://svn.example.com/svn/myproject/source`| SVN Base URL
| *ish_svn_username* | `myuser`             | Username for SVN access
| *ish_svn_password* | `password`           | Password for SVN access
3+| *Git / gitlab-Configuration*
| *ish_gitlab_token* | `yourtoken`          | Token for gitlab access
| *ish_gitlab_server_url* | `https://gitlab.example.com` | Gitlab server URL
| *ish_gitlab_group* | `corporateshop` | Group for the repositories to initialize
| *ish_git_user_name* | `gituser` | username for git user
| *ish_git_user_email* | `gituser@example.com` | email for gituser
3+| *ROLE NEXUS*
| *nexus_ishrepo_url* | `https://repo.intershop.de/content/repository/4711` | Url for access Intershop Repository server
| *nexus_ishrepo_user* | `usertoken` | usertoken for access Intershop Repository server
| *nexus_ishrepo_password* | `secret` | password for usertoken
3+| *ROLE ORACLE-CLIENT*
| *oracle_client_download_url* | `https://install.example.com/oracle/linuxamd64_12102_client.zip` | Location for Oracle client installation file
3+| *ROLE ORACLE-SERVER*
| *oracle_server_download_files* | `- https://install.example.com/oracle/linuxamd64_12102_database_1of2.zip - https://install.example.com/oracle/linuxamd64_12102_database_1of2.zip` | Location for Oracle server installation files
|===

For more information please see

* https://support.intershop.com/kb/index.php/Display/X27327.

== License

Copyright 2014-2016 Intershop Communications.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.