---
- name: create {{oracle_group}} group
  group: name={{oracle_group}}
  
- name: create dba group
  group: name=dba
  
- name: create {{oracle_user}} user
  user: name={{oracle_user}} group={{oracle_group}} groups=dba
  
- name: install unzip
  yum: name=unzip state=present
  
- name: prepare /etc/hosts for use with oracle
  shell: |
    cp /etc/hosts /etc/hosts.ori
    awk '$1~"^127.0.0.1|::1"{$2="'`hostname -s`'\ '`hostname`' "$2}1' OFS="\t" /etc/hosts.ori > /etc/hosts

- name: check {{oracle_server_home}} server installation
  stat: path="{{oracle_server_home}}/bin/sqlplus"
  register: checkoraclehome
  ignore_errors: true
  
- name: include install oracle_server
  include: oracle.yml
  when: checkoraclehome.stat.exists == false

- name: remove Oracle server installation directory
  file: path="{{ installer_dir }}" state=absent
  
- name: create {{oracle_sid}}.environment
  template: src=oraenv.j2 dest=/home/{{oracle_user}}/{{oracle_sid}}.sh owner={{oracle_user}} group={{oracle_group}} mode="0600" 
  
- name: create environment for {{oracle_user}} user
  lineinfile: dest=/home/{{oracle_user}}/.bashrc line="source /home/{{oracle_user}}/{{oracle_sid}}.sh"
  
- name: enable instance in oratab
  lineinfile: dest=/etc/oratab regexp="(^\s*{{oracle_sid}}:{{oracle_server_home}}:)" line="\1Y" backrefs=yes
  
- name: create unit file
  template: src=db_service.j2 dest=/etc/systemd/system/oracledb.service
  register: dbservice
  
- name: reload systemd daemon
  when: dbservice.changed
  shell: systemctl daemon-reload
 
- name: enable service and start oracle
  service: name=oracledb.service enabled=yes state=started
  register: servicestart

# https://docs.oracle.com/database/121/UNXAR/strt_stp.htm#UNXAR150
- name: create auto start-stop script
  template: src=dbora.j2 dest=/etc/init.d/dbora owner={{oracle_user}} group=dba mode="750"
- name: create symbolic for run-level
  file: src=/etc/init.d/dbora dest=/etc/rc.d/rc0.d/K01dbora state=link
- file: src=/etc/init.d/dbora dest=/etc/rc.d/rc3.d/S99dbora state=link
- file: src=/etc/init.d/dbora dest=/etc/rc.d/rc5.d/S99dbora state=link
 
- name: open firewall
  firewalld: port=1521/tcp permanent=true state=enabled immediate=yes

- name: create dbsetup files
  unarchive: src=dbsetup.tar.gz dest=/tmp
  become: yes
  become_user: "{{oracle_user}}"
  register: dbsetupfiles
  
- name: execute dbsetup.sqlplus
  shell: |
    source /home/{{oracle_user}}/{{oracle_sid}}.sh || exit 1
    cd /tmp/dbsetup || exit 1
    sqlplus /nolog @dbsetup.sql
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{oracle_user}}"
  when: dbsetupfiles.changed
