---
- name: check {{installer_dir}}
  stat: path={{installer_dir}}
  register: instdir
  
- name: unpack Oracle server installation archive
  unarchive: src="{{item}}" dest="/tmp" copy=no owner={{oracle_user}} group={{oracle_group}}
  when: instdir.stat.exists == false
  with_items: "{{oracle_server_download_files}}"
    
- name: add kernel parameter
  copy: src=99-oracle.conf dest=/usr/lib/sysctl.d/99-oracle.conf
  
- name: apply kernel parameter
  shell: sysctl -a
  
- name: config limits
  lineinfile: dest=/etc/security/limits.conf line="{{item}}"
  with_items:
    - oracle soft nproc 2047
    - oracle hard nproc 16384
    - oracle soft nofile 1024
    - oracle hard nofile 65536
    
- name: install required packages
  yum: name={{item}} state=present
  with_items:
    - binutils.x86_64
    - compat-libcap1.x86_64
    - gcc.x86_64
    - gcc-c++.x86_64
    - glibc.i686
    - glibc.x86_64
    - glibc-devel.i686
    - glibc-devel.x86_64
    - ksh
    - compat-libstdc++-33
    - libaio.i686
    - libaio.x86_64
    - libaio-devel.i686
    - libaio-devel.x86_64
    - libgcc.i686
    - libgcc.x86_64
    - libstdc++.i686
    - libstdc++.x86_64
    - libstdc++-devel.i686
    - libstdc++-devel.x86_64
    - libXi.i686
    - libXi.x86_64
    - libXtst.i686
    - libXtst.x86_64
    - make.x86_64
    - sysstat.x86_64
    - xorg-x11-xauth.x86_64
    - xorg-x11-utils.x86_64

- name: update Oracle server installation config
  template:
    src: db_install.rsp.j2
    dest: "{{ response_file }}"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0640
    
- name: install Oracle server
  become_user: "{{ oracle_user }}"
  become: yes
  command: "{{ installer_script }} {{ installer_opts }} {{ response_file }}"
  args:
    creates:"{{oracle_server_home}}"
  register: server_install
  failed_when: "'{{ success_message }}' not in server_install.stdout"

- name: update Oracle inventory
  command: "{{ oracle_inventory_script }}"
  
- name: execute root script
  command: "{{ oracle_server_home}}/root.sh"
  
- name: create cfgrsp.properties
  template: src=cfgrsp.properties.j2 dest={{oracle_cfgrsp}} owner={{oracle_user}} group={{oracle_group}} mode=0600

- name: execute configtoool
  shell: "{{oracle_server_home}}/cfgtoollogs/configToolAllCommands RESPONSE_FILE={{oracle_cfgrsp}}"
  become_user: "{{ oracle_user }}"
  become: yes
