---
- name: set git facts
  set_fact:
    gitlab_servername: "{{ish_gitlab_server_url|regex_replace('^.*?://(.*?)', '\\1')}}"
- name: install git
  yum: name=git state=present

- name: install git-svn
  yum: name=git-svn state=present

- name: install pyapi-gitlab
  shell: easy_install pip && pip install pyapi-gitlab

- name: install .gitconfig
  template: src=item.j2 dest={{ish_home}}/.gitconfig owner={{ish_user}} group={{ish_group}}
  with_items: "{{ish_git_config}}"

- name: get ssh-host-keys
  shell: |
    ssh-keyscan {{gitlab_servername}} >> .ssh/known_hosts
    mv .ssh/known_hosts .ssh/known_hosts_tmp
    cat .ssh/known_hosts_tmp | sort -u > .ssh/known_hosts
    rm .ssh/known_hosts_tmp
  args:
    chdir: "{{ish_home}}"
  become: yes
  become_user: "{{ish_user}}"

- name: create gitrepo
  include: gitrepo.yml
  with_items:
    - "{{ish_repos}}"