---
- name: set facts
  set_fact: 
    reponame: "{{outer_item.gitrepo}}"
    srcdir: "{{outer_item.src}}"
    gitlabci: "{{outer_item.gitlabci}}"
    gitignore: "{{outer_item.gitignore}}"

- debug:
    msg: "################################## REPONAME: {{reponame}} #####################################################################"

- name: create gitlab project
  local_action: gitlab_project
                login_token={{ish_gitlab_token}}
                group={{ish_gitlab_group}}
                server_url={{ish_gitlab_server_url}}
                name={{reponame}}
                state=present

- name: write .gitlab-ci.yml
  template: src=item.j2 dest={{srcdir}}/.gitlab-ci.yml
  with_items: "{{gitlabci}}"
  when: gitlabci != '' and ish_gitlab_runner_install
  become: yes
  become_user: "{{ish_user}}"
  no_log: True

- name: write .gitattributes
  template: src=item.j2 dest={{srcdir}}/.gitattributes
  with_items: "{{ish_gitattributes}}"
  become: yes
  become_user: "{{ish_user}}"
  no_log: True

- name: write .gitignore
  template: src=item.j2 dest={{srcdir}}/.gitignore
  with_items: "{{gitignore}}"
  become: yes
  become_user: "{{ish_user}}"
  no_log: True


- name: force reinitialization
  file: dest={{srcdir}}/.git state=absent

- name: initialize gitlab
  shell: |
    git init
    git remote add origin git@{{gitlab_servername}}:{{ish_gitlab_group}}/{{reponame}}.git
    git add .
    git commit -m "Initial commit"
    git push -u origin master
  args:
    chdir: "{{srcdir}}"
  become: yes
  become_user: "{{ish_user}}"